name: wallet_manager
description: "A pixel-perfect, high-performance Money Manager expense tracking app built with Flutter, SQLite offline-first ledger, Google Drive sync, and GitHub Releases OTA in-app updater."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Local SQLite Relational Database
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0

  # High Performance Interactive Charts
  fl_chart: ^0.68.0

  # Date, Time & Number Formatting
  intl: ^0.19.0

  # Biometric & Passcode Security
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2

  # Receipt Photo Capture
  image_picker: ^1.1.2

  # OTA Updater & Networking
  dio: ^5.7.0
  open_filex: ^4.5.0
  package_info_plus: ^8.0.2

  # Cloud Backup & Google Drive Integration
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # CSV & Excel Export / Import & Sharing
  csv: ^6.0.0
  share_plus: ^10.0.2
  file_picker: ^8.1.2

  # Utilities & Permissions
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - icon-192.png
    - icon-512.png
